package com.gospell.drm.drmman;


public enum CommandEnums 
{
	/*-----------------------------------------------------------------------*/
	// system 相关
	/*-----------------------------------------------------------------------*/
	CMD_SYS_ERR, //0
	CMD_SYS_ASK_CONNECT,                
	CMD_SYS_CLOSE_CONNECT,
	CMD_SYS_INITIAL_LANCH,
	CMD_SYS_INITIAL_DVB,               
	CMD_SYS_DEINITIAL_DVB,              	
	CMD_SYS_GET_TIME,
	CMD_SYS_GET_MODEL_INFO,				
	CMD_SYS_GET_STB_ID,
	CMD_SYS_GET_OTA_ID,
	CMD_SYS_GET_SW_VERSION,
	CMD_SYS_GET_HW_VERSION,
	CMD_SYS_GET_SW_RELEASE_DATE,     	
	CMD_SYS_GET_LOADER_INFO_BY_ENV_NAME,
	CMD_SYS_START_UPGRADE_SW,
	CMD_SYS_MANUAL_UPGRADE_SYSTEM,
	CMD_SYS_REBOOT_SYSTEM,		
	CMD_SYS_GET_LOGO_IMAGE_INFO,
	CMD_SYS_GET_AUDIO_MODE,
	CMD_SYS_SET_AUDIO_MODE,
	CMD_SYS_GET_CURRENT_DT,
	CMD_SYS_GET_PLAY_STATUS,
	CMD_SYS_GET_STBBIND_STATUS,
	CMD_SYS_GET_CA_TYPE,
	CMD_SYS_GET_CONTRSOL_INFOR,
	CMD_SYS_GET_GOSAD_STATUS,
	CMD_SYS_GET_GOSAD_INFOR,
	CMD_SYS_SET_AVPLAY_WINDOW,
	CMD_SYS_GET_OTA_VERSION,
	/*-----------------------------------------------------------------------*/
	// 搜索相关
	/*-----------------------------------------------------------------------*/
	CMD_SEARCH_START_MANUAL, 
	CMD_SEARCH_START_NIT,
	CMD_SEARCH_START_S2_MANUAL,
	CMD_SEARCH_START_AUTO, 
	CMD_SEARCH_START_BLIND, 
	CMD_SEARCH_START_FULL,				
	CMD_SEARCH_STOP,
	CMD_SEARCH_GET_STATUS,
	CMD_SEARCH_GET_RESULT,
	CMD_SEARCH_GET_SERVICE_INFO,
	CMD_SEARCH_GET_PARAMS,				
	CMD_SEARCH_REMEMBER_SORT,			
	CMD_SEARCH_GET_SORT_STATUS,
	CMD_SEARCH_GET_FULL_SEARCH_PARAMS,	
	
	/*-----------------------------------------------------------------------*/
	// DVB_S2卫星相关
	/*-----------------------------------------------------------------------*/
	CMD_DB_S2_GET_TOTAL_SAT_NUMBER, 
	CMD_DB_S2_GET_SAT_DATA,
	CMD_DB_S2_GET_SAT_NAME,
	CMD_DB_S2_GET_CURRENT_SAT_INDEX,
	CMD_DB_S2_MODIFY_SAT_DATA,
	CMD_DB_S2_ADD_ONE_SAT,
	CMD_DB_S2_DEL_ONE_SAT,
	CMD_DB_S2_GET_SAT_LIST,	
	CMD_DB_S2_SET_ANT_POSITION,
	CMD_DB_S2_GET_ANT_POSITION, 
	
	/*-----------------------------------------------------------------------*/
	// TP相关
	/*-----------------------------------------------------------------------*/
    CMD_DB_TP_GET_TOTAL_NUMBER_ONESAT,        
    CMD_DB_TP_GET_DATA_BY_INDEX,
    CMD_DB_TP_CURRENT_INDEX,    
	CMD_DB_TP_GET_CURRENT_SAT_INDEX,
	CMD_DB_TP_MODIFY_DATA, 	
	CMD_DB_TP_DEL_ONE_TP, 	
	CMD_DB_TP_ADD_ONE_TP, 
	CMD_DB_TP_GET_TOTAL_TP_NUMBER,
	
	/*-----------------------------------------------------------------------*/
	// 节目操作相关
	/*-----------------------------------------------------------------------*/
	CMD_DB_PROG_SET_CURRENT_LIST,		
	CMD_DB_PROG_GET_CURRENT_LIST,		
	CMD_DB_PRO_GET_ONE_LIST_SERVICE_NUM,   			
	CMD_DB_PROG_GET_CURRENT_LIST_NUMBER,
	CMD_DB_PROG_GET_CURRENT_SERVICE_INDEX,		
	CMD_DB_PROG_GET_SERVICE_INFO,   
	CMD_DB_PROG_DELETE_ONE_SERVICE,
	CMD_DB_PROG_DELETE_ALL_SERVICE,				
	CMD_DB_PROG_RENAME_SERVICE,	 				
	CMD_DB_PROG_MODIFY_LOCK_STATUS,				
	CMD_DB_PROG_MODIFY_FAV_FLAG,                   
	CMD_DB_PROG_MOVE_PROGRAM,
	CMD_DB_PROG_PLAY_SERVICE,	
	CMD_DB_PROG_STOP_PLAY_SERVICE,			
	CMD_DB_PROG_NEXT_SERVICE,		
	CMD_DB_PROG_PREV_SERVICE,
	CMD_DB_PROG_GET_LAST_SERVICE_INDEX,
	CMD_DB_PROG_SET_DEFAULT_PROGRAM,			
	CMD_DB_PROG_GET_DEFAULT_PROGRAM,
	CMD_DB_PROG_GET_STREAM_INFO_BY_TYPE,
	CMD_DB_PROG_SET_CUR_PRO_STREAM_BY_TYPE,
	CMD_DB_PROG_GET_CHANNEL_NUMBER,
	CMD_DB_PROG_GET_BAT_NUM,
	CMD_DB_PROG_GET_BAT_LISTNAME,
	CMD_DB_PROG_GET_FAVGROUP_MASK,
	CMD_DB_PROG_GET_LISTINFO_BY_SERVICEID,
	CMD_DB_PROG_GET_CUR_SERVICE_SUBPID,
	//节目检索
	CMD_DB_PROG_GET_SEARCHED_CHANNEL_SAT_INFO,
	CMD_DB_PROG_GET_CHANNEL_INFO_BY_INDEX,
	CMD_DB_PROG_GET_RADIOLOGOAD,
	CMD_DB_PROG_SHOW_RADIOLOGOAD,
	CMD_DB_PROG_CLEAR_IFRAME,
	//节目排序
	CMD_DB_PROG_GET_SORT_TYPE,
	CMD_DB_PROG_SET_SORT_TYPE,
	//编辑节目PID
	CMD_DB_PROG_SET_PID,
	/*-----------------------------------------------------------------------*/
	// TUNER相关
	/*-----------------------------------------------------------------------*/
	CMD_TUNER_GET_FE_STATUS,		
	CMD_TUNER_START_GET_INFO,			
	CMD_TUNER_END_GET_INFO,	
	CMD_TUNER_GET_INFO,            
	CMD_TUNER_LOCK_TP,       
	CMD_TUNER_LOCK_DISH,  
	CMD_TUNER_CONTROL_MOTOR,
	CMD_TUNER_GET_LOCK_STATUS,  
	CMD_TUNER_SET_WORK_MODE,
	CMD_TUNER_GET_WORK_MODE,

	/*-----------------------------------------------------------------------*/
	// EPG 相关
	/*-----------------------------------------------------------------------*/
	CMD_EPG_GET_NOW_AND_NEXT,		
	CMD_EPG_GET_SC_NUMBER,			
	CMD_EPG_GET_SC_BY_INDEX,					
	CMD_EPG_GET_SC_EXTEND,	
	CMD_EPG_SET_PARENT_RATE_SEND_FLAG,

	/*-----------------------------------------------------------------------*/
	// DB USER(用户设置相关)
	/*-----------------------------------------------------------------------*/
	CMD_DB_USER_GET_PIN_CODE,					
	CMD_DB_USER_SET_PIN_CODE,
	CMD_DB_USER_VERIFY_PIN,				 
	CMD_DB_USER_SET_TRANSPARENT,			
	CMD_DB_USER_GET_TRANSPARENT,			
	CMD_DB_USER_SET_BANNER_TIME,			
	CMD_DB_USER_GET_BANNER_TIME,			
	CMD_DB_USER_SET_LANGUAGE,				
	CMD_DB_USER_GET_LANGUAGE,				
	CMD_DB_USER_SET_VOL, //80
	CMD_DB_USER_SET_MUTE_STATE,
	CMD_DB_USER_AV_STREAM_LANG,
	CMD_DB_USER_SET_TIMEZONE,
	CMD_DB_USER_SET_PARENT_LEVEL,
	CMD_DB_USER_GET_PARENT_LEVEL,
	CMD_DB_USER_SET_PARENT_RATE_INIT_FLAG,		
	CMD_DB_USER_SET_MAIN_TP,               
	CMD_DB_USER_GET_MAIN_TP,
	CMD_DB_USER_RESET,							
	CMD_DB_USER_HANDLE_MUTE,					
	CMD_DB_SAVE_DATABASE,
	CMD_DB_SET_ASPECT_RATIO,
	CMD_DB_GET_ASPECT_RATIO,
	CMD_DB_GET_TIMETYPE,
	CMD_DB_GET_DEFAULT_TIMEZONE,
	CMD_DB_GET_FIRSTINIT_VALUE,
	CMD_DB_SET_FIRSTINIT_VALUE,
	/*-----------------------------------------------------------------------*/
	// PVR相关
	/*-----------------------------------------------------------------------*/
	CMD_PVR_START_REC,
	CMD_PVR_PAUSE_REC,
	CMD_PVR_RESUME_REC,
	CMD_PVR_STOP_REC,
	CMD_PVR_REC_CHECK_USB,
	CMD_PVR_START_TIMESHIFT,
	CMD_PVR_PAUSE_TIME_SHIFT,
	CMD_PVR_STOP_TIMESHIFT,
	CMD_PVR_SPEED_TIMESHIFT,
	CMD_PVR_GET_TIMESHIFT_PLAYTIME,
	CMD_PVR_RESUME_TIMESHIFT,
	CMD_PVR_REC_GET_USBINFO,	
	
	CMD_PVR_PLAYER_INIT,
	CMD_PVR_PLAYER_DEINIT,
	CMD_PVR_PLAYER_START,
	CMD_PVR_PLAYER_PAUSE,
	CMD_PVR_PLAYER_RESUME,
	CMD_PVR_PLAYER_STOP,
	CMD_PVR_PLAYER_FORWARD,
	CMD_PVR_PLAYER_REWIND,
	CMD_PVR_PLAYER_GET_FILE_INFO,
	CMD_PVR_PLAYER_GET_PLAY_TIME,
	/*-----------------------------------------------------------------------*/
	// SUB TTX相关
	/*-----------------------------------------------------------------------*/
	CMD_SUBTTX_GET_STREAM_INFO,
	CMD_SUBTTX_TTX_START,								
	CMD_SUBTTX_TTX_STOP,							
	CMD_SUBTTX_SUB_START,						
	CMD_SUBTTX_SUB_STOP,
	CMD_SUBTTX_SUB_CLOSE,
	CMD_SUBTTX_GET_SUB_OPENFLAG,
	CMD_SUBTTX_TTX_SET_CMD,	
	CMD_SUBTTX_GET_STREAM_NUM,
	
	/*-----------------------------------------------------------------------*/
	// CA相关
	/*-----------------------------------------------------------------------*/	
	//gos ca
	CMD_GOSCA_GET_CARD_INFO,			
	CMD_GOSCA_VERIFY_PIN,				
	CMD_GOSCA_MODIFY_PIN,					
	CMD_GOSCA_GET_TOTAL_EMAIL_INFO, 
	CMD_GOSCA_GET_EMAIL_TITLE,
	CMD_GOSCA_GET_EMAIL_CONTENT,			
	CMD_GOSCA_SET_EMAIL_READ,				
	CMD_GOSCA_DEL_EAMIL,					
	CMD_GOSCA_DEL_ALL_EMAIL,				
	CMD_GOSCA_GET_SERVICE_ENTITLES,		
	CMD_GOSCA_OTHER_SET,                         
	CMD_GOSCA_GET_STATUS,                       
	CMD_GOSCA_CARD_PAIR,  
	CMD_GOSCA_GET_CENTER_FRE,
	CMD_GOSCA_SET_CENTER_FRE,
	CMD_GOSCA_GET_ENCRYPT_FRE,
	CMD_GOSCA_SET_ENCRYPT_FRE,
	CMD_GOSCA_GET_STBBIND_CARDINFO,
	CMD_GOSCA_GET_STBBIND_STBINFO,
	CMD_GOSCA_GET_SERIALNUM_RUNAREA,
	//taihe ca
	CMD_TAIHE_CA_ORDER_IPPV_BY_EVENT_ID,
	CMD_TAIHE_CA_ORDER_PPT_BY_EVENT_ID,
	CMD_TAIHE_CA_VERIFY_PIN, 
	CMD_TAIHE_CA_MODIFY_PIN,
	CMD_TAIHE_CA_GET_VIEW_LEVEL,
	CMD_TAIHE_CA_SET_VIEW_LEVEL,
	CMD_TAIHE_CA_TEMP_VIEW_RIGHT,
	CMD_TAIHE_CA_GET_EMAIL_NUMS,
	CMD_TAIHE_CA_GET_EMAIL_INFO_BY_IDX,
	CMD_TAIHE_CA_GET_EMAIL_CONTENT_BY_IDX,
	CMD_TAIHE_CA_SET_EMAIL_READED_BY_IDX,
	CMD_TAIHE_CA_DEL_EMAIL_BY_IDX,
	CMD_TAIHE_CA_DEL_ALL_EMAILS,
	CMD_TAIHE_CA_GET_PPC_EVENTS,
	CMD_TAIHE_CA_GET_PURSE_BALANCE,
	CMD_TAIHE_CA_GET_UDRM_INFO,
	CMD_TAIHE_CA_GET_ONE_PPV_EVENT_BY_IDX,
	CMD_TAIHE_CA_GET_IPPV_EVNETS_NUMS,
	CMD_TAIHE_CA_GET_ONE_IPPV_EVENT_BY_IDX,
	CMD_TAIHE_CA_GET_PPT_EVNETS_NUMS,
	CMD_TAIHE_CA_GET_ONE_PPT_EVENT_BY_IDX,
	CMD_TAIHE_CA_GET_PPV_EVENTS_NUMS,
	
	//grif ca
	CMD_GRIF_CA_VERIFY_PIN,
	CMD_GRIF_CA_SET_MATURITY_RATE,
	CMD_GRIF_CA_GET_SERVICE_ENTITLES,
	CMD_GRIF_CA_GET_ALL_EVENTS,
	CMD_GRIF_CA_GET_PURSE_BALANCE,
	CMD_GRIF_CA_GET_CARD_INFO,
	CMD_GRIF_CA_MODIFY_PIN,
	
	//conax ca
	CMD_CNXCA_GET_SERVICE_ENTITLES,				
	CMD_CNXCA_GET_ALL_EVENTS,
	CMD_CNXCA_GET_ALL_PURSE,
	CMD_CNXCA_GET_DEBITS_BY_PURSE,
	CMD_CNXCA_GET_CREDITS_BY_PURSE,
	CMD_CNXCA_VERIFY_PIN,
	CMD_CNXCA_MODIFY_PIN,
	CMD_CNXCA_CHG_MATURITY_LEVEL,
	CMD_CNXCA_GET_CARD_INFO,		
	CMD_CNXCA_CHECK_CAPIN,
	
	//biss
	CMD_BISS_GET_BISSKEY_NUMBERS,
	CMD_BISS_GET_BISSKEY_INDEX_LIST,
	CMD_BISS_GET_BISSKEY_BYINDEX,
	CMD_BISS_MODIFY_BISSKEY,
	CMD_BISS_DEL_BISSKEY,
	CMD_BISS_ADD_BISSKEY,

	//mosaic
	CMD_MOSAIC_INIT,
	CMD_MOSAIC_DEINIT,
	CMD_MOSAIC_ONKEYDOWN,
	CMD_STB_CLOSE_CONNECT,
	
	//
	CMD_SYS_DB_TO_USB,
	CMD_SYS_DB_FROM_USB,
	CMD_ZOOM_ONKEYDOWN,
	CMD_PVR_GET_TIMESHIFT_RECTIME,
	CMD_SYS_SET_TIME_OTA,	
	CMD_BISS_MODIFY_BISSKEY_EX,
	CMD_BISS_KEY_TO_USB,
	CMD_BISS_KEY_FROM_USB,
	CMD_GOSCA_GET_CA_ENTITLE_COUNT,
	CMD_GOSAD_SHOW_LOGOAD,
	CMD_PVR_GET_SCRAMBLE_VIDEO_TIME,
	CMD_SYS_GET_INDIA_MARKET,
	CMD_DB_PRO_SET_CUR_LIST_PLAY_SERVICE_IDX,
	CMD_DB_PROG_GETLISTINDEX_BY_INPUT_NUMBER,
	CMD_DB_SYS_GET_REMOTETYPE,
	CMD_SEARCH_SET_INTERRUPT,
	CMD_SYS_GET_OTA_DEF_PARAM,
	CMD_SYS_SET_OTA_DEF_PARAM,
	CMD_SYS_GET_RF_INFO,
	CMD_SYS_SET_RF_INFO,
	CMD_SUBTTX_CC_START_STOP,
	CMD_SYS_SHOWTIME_ON_FRONTPANEL,
	CMD_DB_USER_GET_VOL,
	CMD_SEARCH_CLEAR_PRO_LIST,
	CMD_CA_GET_SCRAMBLE_PLAY_FLAG,
	CMD_SYS_GET_USER_LEGAL_STATUS,
	CMD_DB_PRO_GET_ALL_SERVICE_NUMBER;
	

	public int getValue()
	{
		return this.ordinal();
	}	
}
